### ISSUE TITLE
Spotify Lyrics Domain

### ISSUE THREAD

**Issue by InvalidNoah** [nsde/api#1]
Moin, ich wollt fragen welche Spotify Lyrics Website du für deine Lyrics API nutzt?

**Comment by nsde** [comment]
> Moin, ich wollt fragen welche Spotify Lyrics Website du für deine Lyrics API nutzt?

Schön, mal was von dir zu hören nach so langer Zeit! :)
https://github.com/akashrchandran/spotify-lyrics-api
